# Generated by Django 5.0.1 on 2024-01-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentform',
            table=None,
        ),
    ]
