# Generated by Django 5.0.1 on 2024-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_studentform_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='certification_name',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='company',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='current_profession',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='education_details',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='email',
            field=models.EmailField(default='Not available', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='interest',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='language_name',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='location',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='name',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='phone',
            field=models.CharField(default='Not available', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='skill_name',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='urls',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='work_title',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
